FROM node:21.7.3-alpine3.19 AS ui-build
WORKDIR /usr/src/app
COPY frontend/ ./frontend/
RUN cd frontend && npm install && npm run-script build

FROM node:21.7.3-alpine3.19 AS server-build
WORKDIR /root/
COPY --from=ui-build /usr/src/app/frontend/build ./frontend/build
COPY server/package*.json ./backend/
RUN cd backend && npm install
COPY server/server.js ./backend/

EXPOSE 4000

CMD ["node", "./backend/server.js"]