FROM node:23.11.1-alpine AS ui-build
WORKDIR /usr/src/app/frontend
COPY frontend/ ./
RUN npm install && npm run build

FROM node:23.11.1-alpine AS server-build
LABEL org.opencontainers.image.source="https://github.com/N5GEH/n5geh.tools.apiTokenWebsite"
RUN apk add git
WORKDIR /root/
COPY --from=ui-build /usr/src/app/frontend/build ./frontend/build
COPY server/package*.json ./backend/
RUN cd backend && npm install
COPY server/server.js ./backend/

EXPOSE 4000

CMD ["node", "./backend/server.js"]